### PR TITLE
fix: Updated sgx driver download urls. Fixes issue 2743

### LINKED ISSUE #2743: SGX driver installation fails
It appears that recent updates to Ubuntu 18.04-LTS have broken the current SGX driver installation:

```
# /opt/azure/containers/oe/sgx_linux_x64_driver_1.12_c110012.bin
Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-fJlmmM /home/azureuser
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
cp -r package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
/home/azureuser

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' sign KDIR=/lib/modules/5.0.0-1031-azure/build...(bad exit status: 2)
ERROR (dkms apport): binary package for sgx: 1.12 not found
Error! Bad return status for module build on kernel: 5.0.0-1031-azure (x86_64)
Consult /var/lib/dkms/sgx/1.12/build/make.log for more information.
```

### PR DESCRIPTION
**Pull request by yakman2020**
**Reason for Change**:
Update sgx driver download urls

**Issue Fixed**:
Fixes #2743

### CODE REVIEW

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 1]
```diff
@@ -125,10 +125,10 @@ installSGXDrivers() {
     VERSION=$(grep DISTRIB_RELEASE /etc/*-release| cut -f 2 -d "=")
     case $VERSION in
     "18.04")
-        SGX_DRIVER_URL="https://download.01.org/intel-sgx/dcap-1.2/linux/dcap_installers/ubuntuServer18.04/sgx_linux_x64_driver_1.12_c110012.bin"
+        SGX_DRIVER_URL="https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.21.bin"
```
Comment (mboersma) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]: Is this URL going to break when there's a new `sgx_linux` driver release? I'm guessing from the contents of https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/ubuntuServer18.04/ that the 1.22 release (for example) would replace this one,

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 2]
```diff
@@ -125,10 +125,10 @@ installSGXDrivers() {
...
         ;;
     "16.04")
-        SGX_DRIVER_URL="https://download.01.org/intel-sgx/dcap-1.2/linux/dcap_installers/ubuntuServer16.04/sgx_linux_x64_driver_1.12_c110012.bin"
+        SGX_DRIVER_URL="https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.21.bin"
```
Comment (mboersma) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]: This should refer to the Ubuntu 16.04 package, not 18.04.

File: pkg/engine/templates_generated.go [hunk 3]
```diff
@@ -35635,10 +35635,10 @@ installSGXDrivers() {
     VERSION=$(grep DISTRIB_RELEASE /etc/*-release| cut -f 2 -d "=")
     case $VERSION in
     "18.04")
-        SGX_DRIVER_URL="https://download.01.org/intel-sgx/dcap-1.2/linux/dcap_installers/ubuntuServer18.04/sgx_linux_x64_driver_1.12_c110012.bin"
+        SGX_DRIVER_URL="https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.21.bin"
         ;;
     "16.04")
-        SGX_DRIVER_URL="https://download.01.org/intel-sgx/dcap-1.2/linux/dcap_installers/ubuntuServer16.04/sgx_linux_x64_driver_1.12_c110012.bin"
+        SGX_DRIVER_URL="https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.21.bin"
```
Comment (mboersma) [inline pkg/engine/templates_generated.go]: Same as above--shouldn't this point to the 16.04 package?

File: test/e2e/test_cluster_configs/sgx.json [hunk 4]
```diff
@@ -0,0 +1,51 @@
+{	
+    "env": {	
+        "REGION_OPTIONS": "westeurope",	
+        "GINKGO_SKIP": "should have healthy time synchronization|should create a pv by deploying a pod that consumes a pvc"	
+    },	
+    "options": {	
+        "allowedOrchestratorVersions": [	
+            "1.13",
```
Comment (mboersma) [inline test/e2e/test_cluster_configs/sgx.json]: We're not testing Kubernetes 1.13 as of #2749.

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 1 above)
Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: @mboersma you are assuming based on the presence of a single versioned artifact in that directory that only one at a time ever lives there?

Comment (mboersma) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: Yes, although I could be wrong.

Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: @yakman2020 can you confirm whether or not this URL will be resilient when the next version drops?

Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: Given that SGX drivers installation is currently broken we'll merge this as-is, with the understanding that it may break again in the future
