### PR TITLE
fix: delete hyperkube images before starting kubelet

### LINKED ISSUE #679: kube-proxy stuck in ContainerCreating
We're seeing this regularly across our E2E tests:

```
kube-system   kube-proxy-29jv2                                1/1     Running             0          32m     10.239.255.241   k8s-master-35441517-2   <none>           <none>
kube-system   kube-proxy-5zf7s                                1/1     Running             0          3m27s   10.239.2.35      k8s-agent2-35441517-1   <none>           <none>
kube-system   kube-proxy-996r5                                1/1     Running             0          11m     10.239.1.4       k8s-agent1-35441517-1   <none>           <none>
kube-system   kube-proxy-bx6gc                                0/1     ContainerCreating   0          46m     10.239.255.239   k8s-master-35441517-0   <none>           <none>
kube-system   kube-proxy-xsmrn                                1/1     Running             0          40m     10.239.255.240   k8s-master-35441517-1   <none>           <none>
```

See a single kube-proxy not able to be fully reconciled on a single node.

Pod logs aren't interesting:

```
2019/03/07 18:40:59 $ k logs kube-proxy-bx6gc -c kube-proxy -n kube-system
2019/03/07 18:40:59 #### $ k logs kube-proxy-bx6gc -c kube-proxy -n kube-system completed in 376.260953ms
2019/03/07 18:40:59 
Error from server (BadRequest): container "kube-proxy" in pod "kube-proxy-bx6gc" is waiting to start: ContainerCreating
```

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

Deleting hyperkube images in close proximity to bringing the kubelet online may trick the kubelet into thinking that it has a local image, which if it suddenly doesn't a few ticks later, puts that scheduling operation into an unrecoverable state.

This PR moves container image cleanup to the beginning of the CSE implementation, prior to the bootstrapping of the Kubernetes application layer, to prevent races between Kubernetes container scheduling and underlying container runtime image manipulation.

The time to do these image cleanup operations can be up to 30 seconds, and so we will continue to send the `docker rmi` processes to the background. By moving the commencement of execution to the beginning of CSE we will eliminate *most* of the flaky symptoms due to the race condition described above (which are already a low % of observed operations). The only way to entirely eliminate this race condition via CSE would be to block on image cleanup; that would add 20-30 seconds to each node bootstrap operation, which we do not want to do.

**Issue Fixed**:

Fixes #679

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
The practical effect is an additional ~5-6 GB of data for the duration of the delay period until the older hyperkube images are deleted.

Before deletion:

```
azureuser@k8s-master-66023123-0:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           796M  1.4M  795M   1% /run
/dev/sda1        30G   14G   16G  47% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sdb1        50G   52M   47G   1% /mnt
/dev/sdc1       252G  185M  239G   1% /var/lib/etcddisk
tmpfs           796M     0  796M   0% /run/user/1001
```

After deletion:

```
azureuser@k8s-master-66023123-0:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           796M  1.4M  795M   1% /run
/dev/sda1        30G   14G   16G  47% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sdb1        50G   52M   47G   1% /mnt
/dev/sdc1       252G  185M  239G   1% /var/lib/etcddisk
tmpfs           796M     0  796M   0% /run/user/1001
```

Of course, there is also the side-effect of the vm being rebooted before file deletion, which would abandon the background process forever, and mean that these images would require manual cleanup.

**Comment by jackfrancis** [comment]
Alternatively, we could just do the cleanup inline. Arguably that's the safest thing, although it does add (1) time and perhaps (2) some flakiness as we're reliant upon the `docker` CLI to find and delete images.

But the idea of deleting container images via the docker layer while kubelet is running (whether immediately after or 10 mins later) seems like perhaps the wrong approach.

Thoughts @mboersma @CecileRobertMichon ?

**Comment by jackfrancis** [comment]
Verified that the time duration spent inside the `cleanUpContainerImages` function is negligible:

```
+ cleanUpContainerImages
+ date
Tue Sep 17 17:08:28 UTC 2019
+ '[' false = false ']'
+ echo 'Cleaning up AKS container images, not an AKS cluster'
Cleaning up AKS container images, not an AKS cluster
+ date
+ docker rmi registry:2.7.1
++ grep nginx
Tue Sep 17 17:08:28 UTC 2019
```

☝️ from a test run with the `date` command surrounding the executable code in the func, e.g.:

```
cleanUpContainerImages() {
    date
    # TODO remove all unused container images at runtime
    docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v "${KUBERNETES_VERSION}$" | grep 'hyperkube') &
    docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v "${KUBERNETES_VERSION}$" | grep 'cloud-controller-manager') &
    if [ "$IS_HOSTED_MASTER" = "false" ]; then
        echo "Cleaning up AKS container images, not an AKS cluster"
        docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'hcp-tunnel-front') &
        docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'kube-svc-redirect') &
        docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'nginx') &
    fi

    # TODO: remove once ACR is available on Azure Stack
    docker rmi registry:2.7.1 &
    date
}
```

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 1]
```diff
@@ -275,7 +275,7 @@ cleanUpContainerImages() {
     fi
 
     # TODO: remove once ACR is available on Azure Stack
-    docker rmi registry:2 &
+    docker rmi registry:2.7.1 &
```
Comment (jackfrancis) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]: Cleaning this up while I'm here
