### PR TITLE
fix: lowercase vm name before calling drain node

### LINKED ISSUE #1982: Should always change the node name to lower case before draining it
**Describe the bug**
For VMSS cluster, the virtual machine in Azure (instance name), and the machine name in OS and node name in Kubernetes is different, for example, for VMSS instance with instance id 11
The Instance name in Azure: aks-nodepool1-12345678-vmss_11
The machine name in OS:      aks-nodepool1-12345678-vmss00000B
The node name in Kubernetes: aks-nodepool1-12345678-vmss00000b

The upgrader gets the virtual machines to be upgraded using machine name in OS. So we should change the name to lower case before draining it. Otherwise the draining will fail with 'node not found' error.

https://github.com/Azure/aks-engine/blob/master/pkg/operations/kubernetesupgrade/upgrader.go#L692

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
Ensures that `SafelyDrainNodeWithClient` uses the lowercase version of a VM's name to avoid disagreement between node name and machine name.

**Issue Fixed**:

Fixes #1982 

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

File: pkg/operations/cordondrainvm.go [hunk 1]
```diff
@@ -45,6 +45,7 @@ func SafelyDrainNode(az armhelpers.AKSEngineClient, logger *log.Entry, apiserver
 
 // SafelyDrainNodeWithClient safely drains a node so that it can be deleted from the cluster
 func SafelyDrainNodeWithClient(client armhelpers.KubernetesClient, logger *log.Entry, nodeName string, timeout time.Duration) error {
+	nodeName = strings.ToLower(nodeName)
```
Comment (jackfrancis) [inline pkg/operations/cordondrainvm.go]: I asume this addresses other invocations of `SafelyDrainNodeWithClient` that weren't converting to lowercase in before calling?

Comment (mboersma) [reply pkg/operations/cordondrainvm.go]: Yes. There was only one instance where we weren't coercing it to lowercase, but this should be slightly safer than fixing it before calling.

I looked at a comprehensive fix for VMSS name lowercasing as @CecileRobertMichon suggested, but there are several functions in different structs that should be treated this way and it wasn't a clear win. But I'm happy to revisit if we think a more general solution is warranted.
