### PR TITLE
fix: set kubelet config for containerd in templates

### LINKED ISSUE #1786: containerd scenarios CSE exit 6
For containerd scenarios, we are calling the `wait_for_file` func twice on `/etc/default/kubelet`.

This will always never succeed on the 2nd attemp, as `wait_for_file` is currently implemented to be a "run once to validate that cloud-init has successfully paved the entire file" func, and afterwards it cleans up the sentinel `#EOF` string (which means subsequent invocations of `wait_for_file` will fail, because they will never detect the presence of that string).

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

Simplify containerd kubelet config implementation: do this during cloud-init template generation instead of via sed at the last mile.

Also remove some deprecated "if less than k8s 1.8" logic to make the above more maintainable/expressive.

**Issue Fixed**:

Fixes #1786 

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

File: pkg/api/types.go [hunk 1]
```diff
@@ -1733,6 +1733,11 @@ func (k *KubernetesConfig) GetOrderedKubeletConfigStringForPowershell() string {
 	return strings.TrimSuffix(buf.String(), ", ")
 }
 
+// HasContainerd returns whether or not we need the containerd runtime
+func (k *KubernetesConfig) HasContainerd() bool {
+	return k.ContainerRuntime == KataContainers || k.ContainerRuntime == Containerd
```
Comment (CecileRobertMichon) [inline pkg/api/types.go]: this could be misleading in the future if we assume this function to mean `k.ContainerRuntime == Containerd`, now I understand your original naming `needsContainerd`...  Maybe we can make it explicit in the comment that Kata needs containerd as well so it shows in the function info when hovering from different files, wdyt? Also so we don't think later that this is an unintentional bug...

Comment (CecileRobertMichon) [reply pkg/api/types.go]: other than that lgtm

Comment (jackfrancis) [reply pkg/api/types.go]: I think `needsContainerd` actually is the best option here, with an appropriate comment
