### PR TITLE
fix: front-proxy certs updated by rotate-certs

### LINKED ISSUE #4463: aks-engine rotate-certs is not rotating front proxy certificates
**Describe the bug**

`aks-engine rotate-certs` is not  rotating the front-proxy certs.

**Steps To Reproduce**

Run `rotate-certs` and check that the proxy certs did not change.

**Additional context**

AKS Engine creates a separate PKI for the front-proxy. Failure to rotate the front proxy certs becomes an issue if they expire.

To recover from expired front proxy certificates, follow these steps:

1. On the first control plane node:

```bash
# etcd params
ETCDCTL_ENDPOINTS="${ETCDCTL_ENDPOINTS:=https://127.0.0.1:2379}"
ETCDCTL_CA_FILE="${ETCDCTL_CA_FILE:=/etc/kubernetes/certs/ca.crt}"
ETCD_CA_PARAM="--cacert=${ETCDCTL_CA_FILE}"
ETCDCTL_KEY_FILE="${ETCDCTL_KEY_FILE:=/etc/kubernetes/certs/etcdclient.key}"
ETCDCTL_CERT_FILE="${ETCDCTL_CERT_FILE:=/etc/kubernetes/certs/etcdclient.crt}"
ETCDCTL_PARAMS="--command-timeout=30s --cert=${ETCDCTL_CERT_FILE} --key=${ETCDCTL_KEY_FILE} ${ETCD_CA_PARAM} --endpoints=${ETCDCTL_ENDPOINTS}"
# set key names
ETCD_REQUESTHEADER_CLIENT_CA="/proxycerts/requestheader-client-ca-file"
ETCD_PROXY_CERT="/proxycerts/proxy-client-cert-file"
ETCD_PROXY_KEY="/proxycerts/proxy-client-key-file"
# delete etcd entries
ETCDCTL_API=3 etcdctl ${ETCDCTL_PARAMS} del $ETCD_REQUESTHEADER_CLIENT_CA
ETCDCTL_API=3 etcdctl ${ETCDCTL_PARAMS} del $ETCD_PROXY_KEY
ETCDCTL_API=3 etcdctl ${ETCDCTL_PARAMS} del $ETCD_PROXY_CERT
```

2. On each control plane node:

```bash
source /etc/environment
/etc/kubernetes/generate-proxy-certs.sh
```

### PR DESCRIPTION
**Pull request by jadarsie**
**Reason for Change**:

`aks-engine rotate-certs` is not rotating the front-proxy certs.

AKS Engine creates a separate PKI for the front-proxy as part of node bootstrapping process and delivers them to all nodes  through etcd. To effectively reuse this functionality, `rotate-certs` has to replace the certs stored in etcd.

Also, front-proxy certs now expire after 30 years.

**Issue Fixed**:

Fixes #4463

**Credit Where Due**:

Does this change contain code from or inspired by another project?

- [x] No
- [ ] Yes

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

File: parts/k8s/rotate-certs.sh [hunk 1]
```diff
@@ -37,6 +37,11 @@ cp_certs() {
 
 cp_proxy() {
   source /etc/environment
+  local NODE_INDEX
+  NODE_INDEX=$(hostname | tail -c 2)
+  if [[ $NODE_INDEX == 0 ]]; then
```
Comment (jackfrancis) [inline parts/k8s/rotate-certs.sh:42]: so the idea is that only one control plane node will update the cert, and we are doing this operation serially so the remaining control plane nodes will perform a successful `etcdctl get`?

Comment (jadarsie) [reply parts/k8s/rotate-certs.sh:42]: Correct, it is serial and ordered (master-0 comes first). See the second commit for context/clarification.

File: parts/k8s/cloud-init/artifacts/generateproxycerts.sh [hunk 2]
```diff
@@ -62,13 +62,13 @@ ETCDCTL_API=3 etcdctl ${ETCDCTL_PARAMS} lock ${PROXY_CERTS_LOCK_NAME} >"${PROXY_
 
 pid=$!
 if read -r lockthis <"${PROXY_CERT_LOCK_FILE}"; then
-  if [[ "" == "$(ETCDCTL_API=3 etcdctl ${ETCDCTL_PARAMS} get $ETCD_REQUESTHEADER_CLIENT_CA --print-value-only)" ]]; then
+  if [ "${OVERRIDE_PROXY_CERTS}" = "true" ] || [[ "" == "$(ETCDCTL_API=3 etcdctl ${ETCDCTL_PARAMS} get $ETCD_REQUESTHEADER_CLIENT_CA --print-value-only)" ]]; then
```
Comment (jackfrancis) [inline parts/k8s/cloud-init/artifacts/generateproxycerts.sh:65]: let's use `[[` (double brackets) and `==` (double-equal for equality comparison) to be consistent with the surrounding bash
