### PR TITLE
fix: pause cluster-autoscaler and use VMSS capacity when upgrading

### LINKED ISSUE #401: upgrade broken on VMSS cluster after cluster-autoscaler scale out
Repro steps:

1) Create a cluster with a VMSS agent pool
2) Apply cluster-autoscaler configuration to the above agent pool
3) Manually (or via HPA) scale out pod count in cluster to engage cluster-autoscaler node scale out
4) With the pod count stable, and the new, higher agent pool node count stable, attempt an `aks-engine upgrade`

This is what I got:

```
$ bin/aks-engine upgrade --subscription-id 3014546b-7d1c-4f80-8523-f24a9976fe6a --deployment-dir _output/kubernetes-westus2-96693 --location westus2 --resource-group kubernetes-westus2-96693 --upgrade-version 1.11.7 --vm-timeout 20 --auth-method client_secret --client-id f8497fa4-60fb-4411-99b3-4e7e5a746482 --client-secret ce3c326d-d944-458c-a930-df186270af48
INFO[0003] Upgrading cluster with name suffix: 23427335 
INFO[0003] VM k8s-agentpool1-23427335-vmss_0 in VMSS k8s-agentpool1-23427335-vmss has a current version of 1.11.6 and a desired version of 1.11.7. Upgrading this node. 
INFO[0003] VM k8s-agentpool1-23427335-vmss_1 in VMSS k8s-agentpool1-23427335-vmss has a current version of 1.11.6 and a desired version of 1.11.7. Upgrading this node. 
INFO[0003] VM k8s-agentpool1-23427335-vmss_2 in VMSS k8s-agentpool1-23427335-vmss has a current version of 1.11.6 and a desired version of 1.11.7. Upgrading this node. 
INFO[0004] Master VM name: k8s-master-23427335-0, orchestrator: 1.11.6 (MasterVMs) 
INFO[0004] Upgrading to Kubernetes version 1.11.7       
INFO[0004] Master nodes StorageProfile: ManagedDisks    
INFO[0004] Prepping master nodes for upgrade...         
INFO[0004] Resource count before running NormalizeResourcesForK8sMasterUpgrade: 11 
INFO[0004] Evaluating if agent pool: master, resource: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')))] needs to be removed 
INFO[0004] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))] needs to be removed 
INFO[0004] Evaluating if extension: [concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/computeAksLinuxBilling')] needs to be removed 
INFO[0004] Resource count after running NormalizeResourcesForK8sMasterUpgrade: 11 
INFO[0004] Total expected master count: 1               
INFO[0004] Master nodes that need to be upgraded: 1     
INFO[0004] Master nodes that have been upgraded: 0      
INFO[0004] Starting upgrade of master nodes...          
INFO[0004] masterNodesInCluster: 1                      
INFO[0004] Upgrading Master VM: k8s-master-23427335-0   
INFO[0004] fetching VM: kubernetes-westus2-96693/k8s-master-23427335-0 
INFO[0004] found nic name for VM (kubernetes-westus2-96693/k8s-master-23427335-0): k8s-master-23427335-nic-0 
INFO[0004] deleting VM: kubernetes-westus2-96693/k8s-master-23427335-0 
INFO[0004] waiting for vm deletion: kubernetes-westus2-96693/k8s-master-23427335-0 
INFO[0154] deleting nic: kubernetes-westus2-96693/k8s-master-23427335-nic-0 
INFO[0154] waiting for nic deletion: kubernetes-westus2-96693/k8s-master-23427335-nic-0 
INFO[0154] deleting managed disk: kubernetes-westus2-96693/k8s-master-23427335-0_OsDisk_1_5cf0fdff0f9a43d9872eb8d2a31868e1 
INFO[0215] Master offset: 0                             
INFO[0215] Master pool set count to: 1 temporarily during upgrade... 
INFO[0215] Starting ARM Deployment (master-19-01-30T09.32.51-566184260). This will take some time... 
INFO[0615] Finished ARM Deployment (master-19-01-30T09.32.51-566184260). Succeeded 
INFO[0615] Master VM: k8s-master-23427335-0 is ready    
INFO[0615] Expected master count: 1, Creating 0 more master VMs 
INFO[0615] Master VM: k8s-master-23427335-0 is ready    
INFO[0615] Master VM: k8s-master-23427335-0 is ready    
INFO[0615] Deploying the agent scale sets ARM template... 
INFO[0615] Starting ARM Deployment (agentscaleset-19-01-30T09.39.31-961808051). This will take some time... 
INFO[0643] Finished ARM Deployment (agentscaleset-19-01-30T09.39.31-961808051). Succeeded 
INFO[0643] Upgrading VMSS k8s-agentpool1-23427335-vmss  
INFO[0643] VMSS k8s-agentpool1-23427335-vmss current capacity is 3 and new capacity will be 4 while each node is swapped 
INFO[1161] Successfully set capacity for VMSS k8s-agentpool1-23427335-vmss 
INFO[1161] Draining node k8s-agentpool1-23427335-vmss000000 
INFO[1161] Node k8s-agentpool1-23427335-vmss000000 has been marked unschedulable. 
INFO[1161] 9 pods need to be removed/deleted            
INFO[1162] heapster-bb8d9677d-p25pd pod successfully evicted 
INFO[1162] kube-dns-7f588f5b5b-sg4sv pod successfully evicted 
INFO[1162] php-apache-f55f56b65-t26b7 pod successfully evicted 
INFO[1162] php-apache-f55f56b65-zq4vn pod successfully evicted 
INFO[1162] php-apache-f55f56b65-nw8tm pod successfully evicted 
INFO[1162] tiller-deploy-88c69b9b-k9jrc pod successfully evicted 
INFO[1162] php-apache-f55f56b65-64crk pod successfully evicted 
INFO[1162] kubernetes-dashboard-7b5859758b-xns2x pod successfully evicted 
INFO[1162] metrics-server-5fdc668b9b-r64r2 pod successfully evicted 
INFO[1162] Deleting VM k8s-agentpool1-23427335-vmss000000 in VMSS k8s-agentpool1-23427335-vmss 
INFO[1283] Successfully deleted VM k8s-agentpool1-23427335-vmss000000 in VMSS k8s-agentpool1-23427335-vmss 
INFO[1560] Successfully set capacity for VMSS k8s-agentpool1-23427335-vmss 
INFO[1560] Draining node k8s-agentpool1-23427335-vmss000001 
ERRO[1560] Error draining VM in VMSS: nodes "k8s-agentpool1-23427335-vmss000001" not found 
FATA[1560] Error upgrading cluster: nodes "k8s-agentpool1-23427335-vmss000001" not found
```

Note in the above case, `k8s-agentpool1-23427335-vmss_0` is the original node from `aks-engine deploy` operation (I created a cluster with a single VMSS agent pool, with a node count of 1). The `k8s-agentpool1-23427335-vmss_1` and `k8s-agentpool1-23427335-vmss_2` nodes (which incidentally are upgraded successfully) are the nodes created by `cluster-autoscaler`.

Note that the failure captured above did not do anything destructive, but it failed to render the node count back to 3 (which it was before the upgrade was initiated):

```
$ kubectl get nodes
NAME                                 STATUS    ROLES     AGE       VERSION
k8s-agentpool1-23427335-vmss000003   Ready     agent     13m       v1.11.7
k8s-agentpool1-23427335-vmss000004   Ready     agent     10m       v1.11.7
k8s-agentpool1-23427335-vmss000005   Ready     agent     13m       v1.11.7
k8s-agentpool1-23427335-vmss000006   Ready     agent     3m        v1.11.7
k8s-master-23427335-0                Ready     master    1h        v1.11.7
```

### PR DESCRIPTION
**Pull request by mboersma**
**Reason for Change**:
Pauses cluster-autoscaler during `aks-engine upgrade` to avoid problems, then resumes it after upgrade completes. Also uses the VMSS `Capacity` field for the agentpool `Count` to avoid off-by-N errors.

**Issue Fixed**:
Fixes #401 
See also #881 and kubernetes/autoscaler#860

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

File: pkg/operations/kubernetesupgrade/upgradecluster.go [hunk 1]
```diff
@@ -88,10 +88,41 @@ func (uc *UpgradeCluster) UpgradeCluster(az armhelpers.AKSEngineClient, kubeConf
...
 
-	if err := uc.getClusterNodeStatus(az, uc.ResourceGroup, kubeConfig); err != nil {
+	var kubeClient armhelpers.KubernetesClient
+	if az != nil {
+		timeout := time.Duration(60) * time.Minute
+		k, err := az.GetKubernetesClient("", kubeConfig, interval, timeout)
+		if err != nil {
+			uc.Logger.Warnf("Failed to get a Kubernetes client: %v", err)
+		}
+		kubeClient = k
```
Comment (jackfrancis) [inline pkg/operations/kubernetesupgrade/upgradecluster.go]: should we assume that `k` will have a valid k8s client object in the `err != nil` case?

Comment (mboersma) [reply pkg/operations/kubernetesupgrade/upgradecluster.go]: Maybe not, but this code is moved from lower down and I hadn't changed it. I'm still not positive if this should be a fatal error (it wasn't previously when we only used the client as a fallback upgrade strategy).

**Comment by itaysk** [comment]
Hi, I get how this fixes #424 (upgrade issue while autoscaler is working) but not how this fixes #401 (upgrade issue after autoscaler has worked). Could you please elaborate if and how this fixes #401?

**Comment by mboersma** [comment]
This may not fix #401 as-is, I was just assuming that disabling cluster-autoscaler during upgrades was a necessary first step to getting `aks-engine upgrade` to work in general. This needs more real-world testing to see what the next things to fix are, which is what I'm doing this week.

**Comment by mboersma** [comment]
I've tested this in several variations of the bug described in #401 and it seems to be working. I'd be happy for any reviews or ideas for more tests.

File: pkg/operations/kubernetesupgrade/upgradecluster.go (hunk 1 above)
Comment (mboersma) [reply pkg/operations/kubernetesupgrade/upgradecluster.go]: We check for `nil` before using it. I think this is consistent with the previous optional use of the kubeClient, and also with `upgrade --force` as I implemented it here.

**Comment by mboersma** [comment]
I'm testing this more in multiple agent pool scenarios and adding more unit test coverage. I see a warning about "failed to copy taints" that then succeeds on the next line, so I need to look into whether that's benign and whether this PR caused it.

File: pkg/operations/kubernetesupgrade/upgradecluster_test.go [hunk 2]
```diff
@@ -382,6 +384,47 @@ var _ = Describe("Upgrade Kubernetes cluster tests", func() {
...
+					mockClient.MakeFakeVirtualMachineScaleSetVM("Kubernetes:1.9.7"),
+					mockClient.MakeFakeVirtualMachineScaleSetVM("Kubernetes:1.9.7"),
+				}
+			}
+
+			Expect(uc.DataModel.Properties.AgentPoolProfiles[0].Count).To(Equal(3))
+			err := uc.UpgradeCluster(&mockClient, "kubeConfig", TestAKSEngineVersion)
+			Expect(err).NotTo(HaveOccurred())
+			Expect(uc.DataModel.Properties.AgentPoolProfiles[0].Count).To(Equal(int(capacity)))
+			Expect(uc.AgentPoolScaleSetsToUpgrade[0].VMsToUpgrade).To(HaveLen(4))
```
Comment (CecileRobertMichon) [inline pkg/operations/kubernetesupgrade/upgradecluster_test.go]: why not use the capacity var here as well?

**Comment by jackfrancis** [comment]
Do we have a handle on why `Gopkg.lock` is modified apart from a purposeful change to `Gopkg.toml`?

**Comment by jackfrancis** [comment]
lgtm pending figuring out vendor cruft

**Comment by mboersma** [comment]
I’m using a new test library subpackage. It was already in Google.toml but actually importing the subpackage causes it to show up in Gopkg.lock after I vendored it in.
