### PR TITLE
fix: don't validate Windows version in update scenario

### LINKED ISSUE #3217: Unable to upgrade Windows cluster
**Describe the bug**
aks-engine upgrade outputs following error:

> Error: loading existing cluster: error parsing the api model: Orchestrator Kubernetes version 1.15.7 does not support Windows

I think it is caused by one change in https://github.com/Azure/aks-engine/pull/2930.
https://github.com/Azure/aks-engine/blob/master/pkg/api/vlabs/validate.go#L1176

**Steps To Reproduce**
Build cluster with Windows pool by AKS-Engine 0.45.0, k8s 1.15.7
Upgrade cluster to 1.16 by AKS-Engine 0.50.0

**AKS Engine version**
0.50.0

**Kubernetes version**
1.15.7

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR doesn't throw a validation error for the Kubernetes Version on a Windows-enabled cluster during scale/upgrade contexts.

**Issue Fixed**:

Fixes #3217

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

**Comment by jackfrancis** [comment]
@marosset I'll do some manual validation on this, but I think functionally this is what we want to address #3217

**Comment by jackfrancis** [comment]
Validated manually

File: pkg/api/vlabs/validate.go [hunk 1]
```diff
@@ -1176,7 +1176,7 @@ func (a *Properties) validateWindowsProfile() error {
 			false,
```
Comment (marosset) [inline pkg/api/vlabs/validate.go:1176]: Should we instead figure out how to plumb in isUpdate here instead of hard-coding the false? 
I think that is the initial cause of the issues.

Comment (marosset) [reply pkg/api/vlabs/validate.go:1176]: (But if that is a lot of work I'm fine with these changes)

Comment (jackfrancis) [reply pkg/api/vlabs/validate.go:1176]: Oh, maybe you're right that that's the way to do this! The current UT in this PR should validate if it's as easy as that.

Comment (marosset) [reply pkg/api/vlabs/validate.go]: Nice - I think I broke this when i was refactoring windows validation in a previous PR :(
