### PR TITLE
fix: use ntp instead of systemd-timesyncd in 18.04

### LINKED ISSUE #1306: Ubuntu 18.04: Timesync stays Idle for a while after boot
Our E2E tests revealed that timesync isn't always Synchronized on all VMs when the cluster initially comes up on Ubuntu 18.04 cluster. The same test passes 100% of the time with Ubuntu 16.04.

Soak tests show that eventually all the VMs have Synchronized `systemd-timesyncd` and that once Synchronized it stays Synchronized without any unreliability. 

```
systemctl status systemd-timesyncd● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 17:32:43 UTC; 7h ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 771 (systemd-timesyn)
   Status: "Idle."
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/systemd-timesyncd.service
           └─771 /lib/systemd/systemd-timesyncd
```

E2E output showing failure:
```
+ [[ 18.04 == \1\8\.\0\4 ]]
+ sudo timedatectl status
+ grep 'systemd-timesyncd.service active: yes'
systemd-timesyncd.service active: yes
+ grep 'System clock synchronized: yes'
+ sudo timedatectl status
       System clock synchronized: yes
+ grep 'RTC in local TZ: no'
+ sudo timedatectl status
                 RTC in local TZ: no
+ grep 'Active: active'
+ sudo systemctl status systemd-timesyncd
   Active: active (running) since Tue 2019-05-14 17:52:27 UTC; 2min 52s ago
+ grep 'Status: "Synchronized to time server'
+ sudo systemctl status systemd-timesyncd
+ exit 1"
```

How to reproduce:
Run E2E with `GINKGO_FOCUS=should have healthy time synchronization` on a cluster built with `aks-18.04` distro.

```
{   "apiVersion": "vlabs",   "properties": {     "orchestratorProfile": {       "orchestratorType": "Kubernetes",       "kubernetesConfig": {         "networkPlugin": "azure"       }     },     "masterProfile": {       "count": 1,       "dnsPrefix": "",       "vmSize": "Standard_D2_v2",       "distro": "aks-18.04"     },     "agentPoolProfiles": [       {         "name": "agentpool1",         "count": 2,         "vmSize": "Standard_D2_v2",         "distro": "aks-18.04"       }     ],     "linuxProfile": {       "adminUsername": "azureuser",       "ssh": {         "publicKeys": [           {             "keyData": ""           }         ]       }     },     "servicePrincipalProfile": {       "clientId": "",       "secret": ""     }   } }
```

### PR DESCRIPTION
**Pull request by jackfrancis**
**Reason for Change**:

This PR changes the 18.04-LTS bootstrap implementation (both VHD and non-VHD) to use the `ntp` package instead of the built-in `systemd-timesyncd`. This is due to a hypothesis that this time synchronization configuration is more reliable.

**Issue Fixed**:

Fixes #1306

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Notes**:

### CODE REVIEW

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 1]
```diff
@@ -11,6 +11,9 @@ APMZ_DOWNLOADS_DIR="/opt/apmz/downloads"
 BPFTRACE_DOWNLOADS_DIR="/opt/bpftrace/downloads"
 UBUNTU_RELEASE=$(lsb_release -r -s)
 UBUNTU_CODENAME=$(lsb_release -c -s)
+if [[ $OS == $UBUNTU_OS_NAME ]]; then
+    UBUNTU_VERSION=$(grep DISTRIB_RELEASE /etc/*-release| cut -f 2 -d "=")
```
Comment (CecileRobertMichon) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]: how is this different from `UBUNTU_RELEASE`?

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 2]
```diff
@@ -65,13 +68,19 @@ installEtcd() {
 
 installDeps() {
     if [[ $OS == $UBUNTU_OS_NAME ]]; then
-      CEPH_COMMON="ceph-common"
-      GLUSTERFS_CLIENT="glusterfs-client"
+        if [[ $UBUNTU_VERSION == "18.04" ]]; then
+            NTP="ntp"
+            systemctl_stop 20 5 10 systemd-timesyncd || exit $ERR_SYSTEMCTL_STOP_FAIL
+            retrycmd_if_failure 120 5 25 systemctl disable systemd-timesyncd || exit $ERR_SYSTEMCTL_STOP_FAIL
```
Comment (CecileRobertMichon) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]: can we put disabling timesyncd in a separate function since it's not actually part of installing any dependencies?

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 1 above)
Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: Like, not in any way:

```
azureuser@k8s-master-59690240-0:~$ lsb_release -r -s
18.04
azureuser@k8s-master-59690240-0:~$ grep DISTRIB_RELEASE /etc/*-release| cut -f 2 -d "="
18.04
```

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 2 above)
Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: I would prefer not to install the ntp package on an OS runtime w/ systemd-timesyncd running and enabled, but maybe that's paranoia?

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 1 above)
Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: fixed, thanks!

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 2 above)
Comment (CecileRobertMichon) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: we can at least extract it into a func and call it from here, just want to make sure installDeps doesn't become an long list of unrelated commands

File: vhd/packer/install-dependencies.sh [hunk 3]
```diff
@@ -46,6 +46,10 @@ cat << EOF >> ${VHD_LOGS_FILEPATH}
   - xz-utils
   - zip
 EOF
+if [[ ${UBUNTU_RELEASE} == "18.04" ]]; then
+  echo "  - ntp" >> ${VHD_LOGS_FILEPATH}
```
Comment (CecileRobertMichon) [inline vhd/packer/install-dependencies.sh]: what about installing this in non-vhd scenarios?

Comment (CecileRobertMichon) [reply vhd/packer/install-dependencies.sh]: nvm found it

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 4]
```diff
@@ -35,6 +35,11 @@ removeContainerd() {
     fi
 }
 
+disableTimeSyncd() {
+    systemctl_stop 20 5 10 systemd-timesyncd || exit $1
```
Comment (CecileRobertMichon) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]: why not just 
```suggestion
    systemctl_stop 20 5 10 systemd-timesyncd || exit $ERR_SYSTEMCTL_STOP_FAIL
```
to stay consistent with the rest of the file? We're not passing in exit codes as args in other CSE functions

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 5]
```diff
@@ -35,6 +35,11 @@ removeContainerd() {
...
+    retrycmd_if_failure 120 5 25 systemctl disable systemd-timesyncd || exit $1
```
Comment (CecileRobertMichon) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]:
```suggestion
    retrycmd_if_failure 120 5 25 systemctl disable systemd-timesyncd || exit $ERR_SYSTEMCTL_STOP_FAIL
```

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 4 above)
Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: Good question! I'm just sort of desparate to save cloud-init bytes here is the reason.

File: parts/k8s/cloud-init/artifacts/cse_install.sh [hunk 6]
```diff
@@ -68,6 +73,10 @@ installDeps() {
         retrycmd_if_failure 60 5 10 dpkg -i /tmp/packages-microsoft-prod.deb || exit $ERR_MS_PROD_DEB_PKG_ADD_FAIL
         aptmarkWALinuxAgent hold
         packages+=" cgroup-lite ceph-common glusterfs-client"
+        if [[ $UBUNTU_RELEASE == "18.04" ]]; then
+            disableTimeSyncd $ERR_SYSTEMCTL_STOP_FAIL
```
Comment (CecileRobertMichon) [inline parts/k8s/cloud-init/artifacts/cse_install.sh]:
```suggestion
            disableTimeSyncd
```

File: parts/k8s/cloud-init/artifacts/cse_install.sh (hunk 4 above)
Comment (CecileRobertMichon) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: in that case maybe we can change `systemctl_stop` to take more than one arg and stop both in one call

Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: I think that's a good suggestion for a follow-up PR, how about my latest change?

Comment (CecileRobertMichon) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: I think it's okay but I really don't like that we have to lower code quality/readability to save space :(

Comment (jackfrancis) [reply parts/k8s/cloud-init/artifacts/cse_install.sh]: :(

**Comment by jackfrancis** [comment]
@yangl900 @xuto2 @palma21 FYI, AKS Engine will be shipping a ntp-enabled (in favor of systemd-timesync) 18.04-LTS on the way towards considering making it the default Ubuntu flavor.

@ritazh FYI
